name: pytorch-cifar-tutorial
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - libjpeg-turbo
  - libpng
  - imageio
  - torchvision
  - matplotlib
  - scikit-learn
  - pytorch-lightning
  - seaborn
  - numpy
  - ipykernel
  - onnx
  - onnxscript
  - onnxruntime
  - pip
  - pip:
    - optuna
    - torch-pruning